export enum Actions {
  CREATE_BOARD = "CREATE_BOARD",
  CHANGE_TURN = "CHANGE_TURN",
  REMOVE_FIGURE = "REMOVE_FIGURE",
  CHANGE_FIGURE_POSITION = "CHANGE_FIGURE_POSITION",
  SET_ACTIVE_FIGURE = "SET_ACTIVE_FIGURE",
  UPDATE_BOARD = "UPDATE_BOARD",
  CAPTURE = "CAPTURE",
}
